# Numpy (Numerical Python)

### Def: Numpy is a open source python library for numerical computations.

In [3]:
# What is the difference between python list and numpy array?
# ans: 1.List are heterogeneous, while numpy array are homogeneous.
# 2. Numpy array are 50x faster then the List.
# 3. In numpy array elements store in continuous memory locations while in list
# 4. Numpy array are good at multiprocessor

# Numpy is designed C, C++ and Python

### Important operations in Numpy
- 1. Installing, upgrading and important numpy
  2. Creating Numpy array's
  3. Special type of numpy array creation
  4. Array shape, reshaping and transpose operation
  5. Size, Datatype and their conversion
  6. Indexing & slicing & modification
  7. Mathematical & statistical operations
  8. Concatination, Stacking, Splitting of numpy
  
  

# 1.Installing, upgrading and important numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
np.__version__

'2.3.4'

# 2. Creating Numpy array's

In [7]:
# 1d array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [8]:
arr = np.array([1,2,3,4,5.5])
print(arr)
print(type(arr))

[1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'>


In [9]:
# data type of elements
arr.dtype

dtype('float64')

In [10]:
arr = np.array([1,2,3, "Hello",5.5])
print(arr)
print(type(arr))
print(arr.dtype)

# U32 means unicode string data of max 32 length

['1' '2' '3' 'Hello' '5.5']
<class 'numpy.ndarray'>
<U32


In [11]:
# 2D numpy array
arr2 = np.array([['rrr', 'bahubali', 'OG'],['NTR', 'Prabhas', 'Pawan']])
arr2

array([['rrr', 'bahubali', 'OG'],
       ['NTR', 'Prabhas', 'Pawan']], dtype='<U8')

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.shape

(2, 3)

In [14]:
# 3d array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.shape

(2, 2, 3)

In [17]:
# 4d array
arr4 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]] )
arr4

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [18]:
arr4.shape

(2, 2, 2, 3)

In [19]:
arr4.ndim

4

# 3. Special type of numpy array creation

In [20]:
# Array of zeros
# 1D Zero numpy array
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [21]:
# 2d zero numpy array
zero_arr = np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# 3d zero numpy array
zero_arr = np.zeros((3,2,3))
zero_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create and initialize the numpy array with 1 (one)
# 1D Ones numpy array
ones_arr = np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [24]:
# 2D array
ones_arr = np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# 3D array
ones_arr = np.ones(((2,2,3)))
ones_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
# filling/initialize the numpy array with specific value

# 1D array with specific value
spe_arr = np.full(5,6000)
spe_arr

array([6000, 6000, 6000, 6000, 6000])

In [27]:
# 2D array with specific value
spe_arr = np.full((3,2),60)
spe_arr

array([[60, 60],
       [60, 60],
       [60, 60]])

In [28]:
# 3D array with specific value
spe_arr = np.full((3,2,3),60)
spe_arr

array([[[60, 60, 60],
        [60, 60, 60]],

       [[60, 60, 60],
        [60, 60, 60]],

       [[60, 60, 60],
        [60, 60, 60]]])

In [29]:
## Identity matrix
# identity matrix is a square matrix

identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random module in numpy

In [30]:
# 1D array of random elements
# rand() function generates uniform distributed values between 0 to 1
np.random.rand(5) # here we take any number

array([0.55517606, 0.2618264 , 0.88127803, 0.81018093, 0.54740762])

In [31]:
# 2D random array with values between 0 to 1 (uniformly distributed)
np.random.rand(2,3)

array([[0.00373274, 0.87378719, 0.64160441],
       [0.14765118, 0.48524659, 0.71606424]])

In [32]:
# 3D matrix
np.random.rand(3,2,3)

array([[[0.99159197, 0.53016321, 0.44078395],
        [0.48733283, 0.50723492, 0.61755077]],

       [[0.09401044, 0.73563409, 0.23407552],
        [0.86044961, 0.86161236, 0.11216492]],

       [[0.49155169, 0.31198396, 0.44908194],
        [0.53512611, 0.58007778, 0.49886938]]])

In [33]:
# 4D matrix
np.random.rand(3,2,3,2)

array([[[[0.27878516, 0.60258625],
         [0.7778527 , 0.39589934],
         [0.0247463 , 0.8454612 ]],

        [[0.39012502, 0.45194578],
         [0.27001052, 0.82806616],
         [0.26563093, 0.26954387]]],


       [[[0.50291874, 0.23536786],
         [0.13217557, 0.97116527],
         [0.29119874, 0.4235669 ]],

        [[0.54195666, 0.36954052],
         [0.28432487, 0.35959513],
         [0.70565586, 0.71403185]]],


       [[[0.34044099, 0.14041242],
         [0.97918028, 0.06235152],
         [0.41745376, 0.45095677]],

        [[0.50991483, 0.13800835],
         [0.49214527, 0.75183357],
         [0.9269124 , 0.02171667]]]])

In [34]:
# random() function
np.random.random(5)

array([0.34648123, 0.81624217, 0.83871033, 0.40665988, 0.50253557])

In [35]:
# 2D
np.random.random((2,3)) # here we use tuple

array([[0.15146268, 0.25529698, 0.05209054],
       [0.30425414, 0.02110276, 0.80289746]])

In [36]:
# 3D
np.random.random((2,3,2))

array([[[0.03743436, 0.08999268],
        [0.03161516, 0.61809492],
        [0.24257033, 0.98742403]],

       [[0.49489892, 0.61383916],
        [0.38058887, 0.6821472 ],
        [0.4533287 , 0.01752269]]])

In [37]:
# randn() : This will generate most of the random values between -3 to +3
# randn() function generates values as standard normal distribution (mean = 0, std = 1)

#1D array
np.random.randn(50)

array([-0.15334502,  0.97656228,  0.97085438, -0.00641561,  0.56157613,
       -0.80218819,  0.51455467,  1.22181906,  0.74906547,  0.93690263,
        1.47464963,  0.69850668,  0.31854296,  1.26055576, -0.38132956,
       -0.37426969,  0.20105453,  0.2620961 , -1.51860144, -0.0955819 ,
       -1.74248973, -0.92750695,  1.17724624, -1.88914412, -0.48536465,
        1.60323906,  1.27985782, -1.00788493, -0.35897509, -0.26728737,
        0.35717287,  1.45945147, -1.24213096, -0.81622949,  0.66478243,
        0.04147554,  2.81416703, -0.44068582,  0.69596637, -0.05177573,
        0.34333116,  0.47261233, -1.19414613, -0.03316729,  0.66837264,
        0.22356354,  0.10447624, -1.36982399,  0.20263482, -0.31616524])

In [38]:
#2D array
np.random.randn(2,3)

array([[ 0.0521403 ,  0.60695677,  0.19277852],
       [-0.9624442 , -1.36296952, -0.30871436]])

In [39]:
#3D array
np.random.randn(2,3,2)

array([[[ 0.05827127,  0.69502192],
        [-0.2538532 , -1.40630764],
        [-0.97026533,  0.92034652]],

       [[ 0.76882184,  0.58605235],
        [ 2.22523916,  0.167064  ],
        [-1.011038  ,  0.28517307]]])

In [40]:
# randint() : generating integer values in a fix range

rand_int_data = np.random.randint(10, 100, 5)  # 10 inclusive , 100 exclusive numbers between 10 to 100 but not 100 and the five is how manyn elements we want to print we take any number
rand_int_data

array([99, 56, 19, 28, 25], dtype=int32)

In [41]:
# 2d array
np.random.randint(10,1000,(2,3))

array([[213, 283, 122],
       [351, 582, 562]], dtype=int32)

In [42]:
# 3d array
np.random.randint(10,1000,(2,3,2)) 

array([[[104, 340],
        [760, 348],
        [956, 371]],

       [[107, 678],
        [395, 179],
        [368, 372]]], dtype=int32)

In [43]:
# choice() : This is used for selecting categorical data

GF = np.array(['Turky', 'Murgi', 'Chuhiya', 'Bakri'])
np.random.choice(GF, size = 3)

array(['Chuhiya', 'Murgi', 'Chuhiya'], dtype='<U7')

In [44]:
np.random.choice(GF, size = 3, replace = False)

array(['Bakri', 'Murgi', 'Chuhiya'], dtype='<U7')

In [45]:
np.random.choice(GF, size = 10, p = [0.4, 0.3, 0.2, 0.1])

array(['Murgi', 'Turky', 'Turky', 'Murgi', 'Turky', 'Turky', 'Murgi',
       'Turky', 'Bakri', 'Turky'], dtype='<U7')

In [46]:
# by using seed its gives different names
np.random.seed(42)
np.random.choice(GF, size = 3)

array(['Chuhiya', 'Bakri', 'Turky'], dtype='<U7')

### create sequences, shuffled, linearly spaced array

In [47]:
arr1 = np.arange(1,10,1) # 1 is inclusive, 10 is exculuded
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# shuffle modify the original array
np.random.shuffle(arr1)
arr1

array([6, 1, 4, 7, 3, 2, 9, 5, 8])

In [49]:
# permutation don't modify the original array
arr2 = np.random.permutation(arr1)
arr2

array([6, 2, 9, 1, 8, 4, 7, 3, 5])

In [50]:
# Generate linear spaced numbers between 1 to 10
arr3 = np.linspace(1,10,5) # linspace(start, end, size) for size we can take any number
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# 4. Array shape, reshaping and transpose operation

In [51]:
# shape() : used to check the dimension of the numpy array
#2d array
cloth_arr = np.array([['Shirt & Dhoti', 'Angvastra', 'Panche'], ['Half Saree', 'Lehenga', 'Silk Saree']])
print(cloth_arr)
print(cloth_arr.shape)

[['Shirt & Dhoti' 'Angvastra' 'Panche']
 ['Half Saree' 'Lehenga' 'Silk Saree']]
(2, 3)


In [52]:
# reshape() 

print(cloth_arr.reshape(3,2))

[['Shirt & Dhoti' 'Angvastra']
 ['Panche' 'Half Saree']
 ['Lehenga' 'Silk Saree']]


In [53]:
print(cloth_arr.reshape(1,6))

[['Shirt & Dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga'
  'Silk Saree']]


In [54]:
print(cloth_arr.reshape(6,1))

[['Shirt & Dhoti']
 ['Angvastra']
 ['Panche']
 ['Half Saree']
 ['Lehenga']
 ['Silk Saree']]


In [55]:
# 3d matrix
print(cloth_arr.reshape(1,2,3))

[[['Shirt & Dhoti' 'Angvastra' 'Panche']
  ['Half Saree' 'Lehenga' 'Silk Saree']]]


In [56]:
# 1d array
print(cloth_arr.reshape(6))

['Shirt & Dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga' 'Silk Saree']


In [57]:
# ravel() : flatten any array to 1d array

oneD_arr = cloth_arr.ravel()
print(oneD_arr)

['Shirt & Dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga' 'Silk Saree']


In [58]:
cloth_arr

array([['Shirt & Dhoti', 'Angvastra', 'Panche'],
       ['Half Saree', 'Lehenga', 'Silk Saree']], dtype='<U13')

In [59]:
# transpose of a matrix : rows becomes column and columns becomes row
print(cloth_arr.T)

[['Shirt & Dhoti' 'Half Saree']
 ['Angvastra' 'Lehenga']
 ['Panche' 'Silk Saree']]


In [60]:
# create a nD array quickly

#5D array
nD_arr = np.arange(1,49).reshape(2, 2, 3, 2, 2)
nD_arr

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]],

         [[ 9, 10],
          [11, 12]]],


        [[[13, 14],
          [15, 16]],

         [[17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24]]]],



       [[[[25, 26],
          [27, 28]],

         [[29, 30],
          [31, 32]],

         [[33, 34],
          [35, 36]]],


        [[[37, 38],
          [39, 40]],

         [[41, 42],
          [43, 44]],

         [[45, 46],
          [47, 48]]]]])

# 5. Size, Datatype and their conversion

In [61]:
# size : use to find  the number of elements in the numpy array

songs = np.array(['Kissik', 'Monica', 'Manohari'])
print(songs.size)
print(cloth_arr.size)
print(nD_arr.size)

3
6
48


In [62]:
# U : unicode string with max 8 length
print(songs.dtype)

<U8


In [63]:
# astype() : for data type conversion
song_duration = np.array([4.32, 5.2, 12.5])
int_arr = song_duration.astype(int)
int_arr

array([ 4,  5, 12])

In [64]:
song_earning = np.array(["4", "500", "1000"])
int_arr = song_earning.astype(int)
int_arr

array([   4,  500, 1000])

In [65]:
song_earning = np.array(["4", "500", "1000"])
float_arr = song_earning.astype(float)
float_arr
print(song_earning.dtype)

<U4


In [66]:
# boolean
np.array([True, False, True]).astype(int)

array([1, 0, 1])

In [67]:
np.array([0, 2, 5, -1]).astype(bool)

array([False,  True,  True,  True])

# 6. Indexing & slicing & modification

In [68]:
sweets = np.array([['Pootharekulu', 'Jangiri', 'coconut laddo'],
                   ['Kaju katli', 'Raava laddo', 'Modakam']])
print(sweets[1,2])

Modakam


In [69]:
print(sweets[0, :])

['Pootharekulu' 'Jangiri' 'coconut laddo']


In [70]:
print(sweets[:, 1])

['Jangiri' 'Raava laddo']


In [71]:
print(sweets[-1, -2])

Raava laddo


In [72]:
print(sweets[-1])

['Kaju katli' 'Raava laddo' 'Modakam']


In [73]:
# modification
sweets[1,1] = 'Payasam'
sweets

array([['Pootharekulu', 'Jangiri', 'coconut laddo'],
       ['Kaju katli', 'Payasam', 'Modakam']], dtype='<U13')

# 7. Mathematical & Stastistical operations

In [74]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr +10)

[[11 12 13]
 [14 15 16]]


In [75]:
print(arr-10)

[[-9 -8 -7]
 [-6 -5 -4]]


In [76]:
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]]


In [77]:
print(arr ** 2)

[[ 1  4  9]
 [16 25 36]]


In [78]:
age = np.array([20, 22, 21, 23, 21, 21, 22, 16, 18, 22, 80, 90, 120, 200])
print(np.sum(age))

696


In [79]:
print(np.min(age))

16


In [80]:
print(np.max(age))

200


In [81]:
print(np.mean(age))

49.714285714285715


In [82]:
print(np.var(age))

2755.918367346939


In [83]:
print(np.std(age))

52.496841498769605


In [84]:
print(np.median(age))

22.0


In [85]:
print(np.percentile(age, 50))

22.0


In [86]:
print(np.quantile(age, 0.50))

22.0


In [87]:
#argmin(): Finding the index of minimum element

age = np.array([20, 22, 21, 23, 21, 21, 22, 16, 18, 22, 80, 90, 120, 200])
print(np.argmin(age))

7


In [88]:
# argmax()
age = np.array([20, 22, 21, 23, 21, 21, 22, 16, 18, 22, 80, 90, 120, 200])
print(np.argmax(age))

13


In [89]:
#log(): finding the log value.

# log1000 (base= 10) = 3

print(np.log10(1000))
print(np.log2(1024))
print(np.log(1000)) # base = e = 2.71

3.0
10.0
6.907755278982137


In [90]:
#sqrt
print(np.sqrt(900))

30.0


In [91]:
pi = 3.1415645
print(np.round(pi,2))

3.14


In [92]:
print(np.floor(pi))

3.0


In [93]:
print(np.ceil(pi))

4.0


In [94]:
print(np.abs(-456))

456


In [95]:
# sorting of numpy array
fruits = np.array(['Arati pandu', 'Mammadi pandu', 'Naarinja', 'Kobbari Kaaya'])
print(np.sort(fruits))

['Arati pandu' 'Kobbari Kaaya' 'Mammadi pandu' 'Naarinja']


In [96]:
fruits_price = np.array([80, 100, 60, 40])
print(np.sort(fruits_price))

[ 40  60  80 100]


In [97]:
print(np.sort(fruits_price)[::-1])

[100  80  60  40]


In [98]:
# 2D array sorting

arr2 = np.array([[10,5,56], [90, 60, 75]])
arr2

array([[10,  5, 56],
       [90, 60, 75]])

In [99]:
print(np.sort(arr2))

[[ 5 10 56]
 [60 75 90]]


# 8. Concatination, Stacking, Splitting of numpy

In [100]:
# concatenate() : This will merge the two or more numpy arrays into one array
# 1D array concatenation
arr1 = np.array([100, 200, 1000])
arr2 = np.array([0, -5, 20])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 100  200 1000    0   -5   20]


In [101]:
# 2D arrays concatenate
# axis = 1 : horizontal concatenation (column wise)

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])

arr_2D = np.concatenate((arr1, arr2), axis = 1)
print(arr_2D)

[[  50   20    2  500 2000  200]
 [   5    8    9  500  800  900]]


In [102]:
# 2D arrays concatenate
# axis = 0 : vertical concatenation (row wise)

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])

arr_2D = np.concatenate((arr1, arr2), axis = 0)
print(arr_2D)

[[  50   20    2]
 [   5    8    9]
 [ 500 2000  200]
 [ 500  800  900]]


In [114]:
# imp point : We cannot concatenate() two different dimension arrays
# a = np.array([1,2,3])
# b= np.array([[4,5,6]])
# np.concatenate((a,b), axis = 0) # either put axis = 0

In [104]:
# We can concatenate below arrays row wise but not column wise

a = np.array([[1,2,3],
              [4,5,6]])  # 2,3
b= np.array([[7,8,9]])  #1,3
np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Stack() function in numpy

#### Def : Stack() function is also used for merging the numpy arrays.
#### Stack() function will add one more extra dimension in final output array

In [105]:
arr1 = np.array([100, 200, 1000])
arr2 = np.array([0, -5, 20])

# axis = 0: row wise stacking
stacked_arr = np.stack((arr1, arr2), axis = 0)
print(stacked_arr)

[[ 100  200 1000]
 [   0   -5   20]]


In [106]:
print(np.concatenate((arr1, arr2)))

[ 100  200 1000    0   -5   20]


In [107]:
# axis = 1 : column wise stacking
stacked_arr = np.stack((arr1, arr2), axis = 1)
print(stacked_arr)


[[ 100    0]
 [ 200   -5]
 [1000   20]]


##### Axis value tell us where to add the new dimension
##### N : number of input array
##### axis = 0: N, a1, a2,....,ak
##### axis = 1: a1,N, a2,.....ak
##### axis = 2: a1,a2,N.....ak

In [108]:
# 2D array stacking
arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])

# axis = 0 : row wise
stacked_2D = np.stack((arr1, arr2), axis = 0)
print(stacked_2D)

[[[  50   20    2]
  [   5    8    9]]

 [[ 500 2000  200]
  [ 500  800  900]]]


In [109]:
# 2D array stacking
arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])

# axis = 1 column wise
stacked_2D = np.stack((arr1, arr2), axis = 1)
print(stacked_2D)

[[[  50   20    2]
  [ 500 2000  200]]

 [[   5    8    9]
  [ 500  800  900]]]


#### vstack(): vertical stacking
- vstack() is same as vertical concatenation

In [115]:
arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])
result = np.vstack((arr1, arr2))
print(result)

[[  50   20    2]
 [   5    8    9]
 [ 500 2000  200]
 [ 500  800  900]]


In [116]:
np.concatenate((arr1, arr2))

array([[  50,   20,    2],
       [   5,    8,    9],
       [ 500, 2000,  200],
       [ 500,  800,  900]])

In [117]:
# hstack() : horizontal stacking
#hstack() is same as horizontal concatenation

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])
result = np.hstack((arr1, arr2))
print(result)


[[  50   20    2  500 2000  200]
 [   5    8    9  500  800  900]]


In [118]:
arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [500, 800, 900]])

arr3 = np.array([[25, 70, 500],
                 [700, 65, 55]])

result = np.hstack((arr1, arr2, arr3))
print(result)


[[  50   20    2  500 2000  200   25   70  500]
 [   5    8    9  500  800  900  700   65   55]]


## Splitting numpy arrays

In [122]:
# split() : used for splitting the big array to small array
Slipper_speed_mom_arr = np.array([10, 20, 30, 100, 35,60, 25, 45,55])
split_arr = np.split(Slipper_speed_mom_arr, 3)
print(split_arr)

[array([10, 20, 30]), array([100,  35,  60]), array([25, 45, 55])]


In [125]:
print(split_arr[0])
print(split_arr[1])
print(split_arr[2])

[10 20 30]
[100  35  60]
[25 45 55]


In [130]:
print(split_arr[0][0])
print(split_arr[1][1])
print(split_arr[2][2])

10
35
55


In [127]:
print(split_arr[1][1])

35


In [132]:
# 2D array
Slipper_speed_mom_arr = np.array([[10, 20], [30, 100], [35,60]])
split_arr = np.split(Slipper_speed_mom_arr, 3)
print(split_arr)
print(type(split_arr))

[array([[10, 20]]), array([[ 30, 100]]), array([[35, 60]])]
<class 'list'>


In [133]:
print(split_arr[0])
print(split_arr[1])
print(split_arr[2])

[[10 20]]
[[ 30 100]]
[[35 60]]


In [140]:
print(split_arr[0][0][0])
print(split_arr[1][0][0])
print(split_arr[2][0][0])

10
30
35


In [141]:
print(split_arr[0][0][0])
print(split_arr[1][0][1])
print(split_arr[2][0][0])

10
100
35
