## Assignment

In [2]:
import numpy as np
import pandas as pd

In [3]:
df_csv=pd.read_csv("Indian_Cricket_Team_Dataset.csv")

In [4]:
df_csv

Player Name  Age  Matches Played  Batting Average  Strike Rate
0       Player_1   26             456            27.70       188.21
1       Player_2   23             154            24.61       139.34
2       Player_3   32             210            36.87       182.79
3       Player_4   34             426            51.81       178.77
4       Player_5   30             221            49.80       162.44
..           ...  ...             ...              ...          ...
995   Player_996   24             279            23.46       187.80
996   Player_997   28             344            29.47       160.55
997   Player_998   23             126            49.30       124.71
998   Player_999   35              16            41.93       135.59
999  Player_1000   30             146            25.12       108.39

[1000 rows x 5 columns]

## 1: Convert 'Age' column to a NumPy array.

In [5]:
np.array(df_csv['Age'])

array([26, 23, 32, 34, 30, 27, 32, 24, 26, 29, 22, 26, 30, 30, 27, 24, 23,
       27, 27, 22, 25, 24, 21, 27, 31, 33, 25, 21, 35, 31, 24, 20, 31, 29,
       25, 32, 31, 28, 20, 30, 30, 34, 29, 35, 31, 31, 35, 34, 33, 33, 34,
       33, 22, 31, 26, 23, 35, 28, 22, 24, 22, 26, 24, 28, 26, 21, 23, 28,
       31, 33, 21, 29, 28, 29, 24, 21, 23, 31, 34, 31, 26, 31, 32, 27, 34,
       22, 33, 20, 23, 21, 27, 23, 21, 33, 25, 25, 29, 23, 25, 32, 34, 21,
       29, 31, 21, 29, 33, 23, 33, 34, 35, 34, 27, 33, 26, 31, 28, 33, 27,
       24, 35, 32, 21, 34, 24, 27, 29, 28, 31, 31, 31, 32, 28, 32, 34, 32,
       20, 28, 26, 28, 27, 20, 31, 27, 27, 34, 30, 22, 20, 27, 22, 22, 20,
       30, 24, 29, 26, 29, 28, 31, 26, 28, 27, 31, 21, 20, 35, 26, 26, 33,
       27, 24, 22, 31, 27, 25, 30, 22, 20, 22, 24, 34, 33, 22, 20, 24, 29,
       26, 34, 33, 26, 30, 28, 34, 34, 29, 29, 31, 32, 22, 34, 35, 26, 20,
       23, 32, 35, 23, 33, 24, 26, 26, 32, 34, 30, 32, 23, 32, 35, 26, 30,
       22, 25, 31, 21, 29

## 2: Find the average age of players.

In [6]:
average_age=np.mean(df_csv['Age'])
print(average_age)

27.57


## 3: Find the oldest and youngest player age.

In [7]:
oldest=np.max(df_csv['Age'])
youngest=np.min(df_csv['Age'])
print('oldest:',oldest)
print('youngest:',youngest)

oldest: 35
youngest: 20


## 4: Count the total number of players above 30 years old.

In [8]:
above_age=np.sum(df_csv['Age']>30)
print(above_age)

336


## 5: Find the median batting average.

In [9]:
batting_avg = np.array([df_csv['Batting Average']])
median_avg = np.median(batting_avg)
print(median_avg)

40.135


## 6: Find the standard deviation of strike rates.

In [10]:
strike_rate=np.array([df_csv['Strike Rate']])
print(strike_rate)

[[188.21 139.34 182.79 178.77 162.44 149.45 197.96 114.5  172.52 119.12
  133.83 130.87 194.7  196.74 118.3  102.2  172.   141.8  108.88 168.38
  154.51 198.05 122.74 140.4  154.25 179.17 154.88 161.29 122.61 184.69
  142.86 114.1  166.42 121.61 109.76 186.2  146.02 174.93 129.06 178.7
  111.19 135.6  197.81 179.4  149.73 133.98 187.21 154.48 175.84 175.41
  101.79 112.63 165.96 116.16 125.55 194.66 156.02 175.07 155.8  155.25
  109.42 134.37 128.24 139.07 179.83 137.19 145.17 139.74 109.34 144.11
  119.56 118.67 109.4  135.67 175.75 127.64 131.23 164.27 119.58 189.7
  152.02 144.76 155.78 116.6  161.35 136.31 189.72 116.89 150.71 159.81
  103.34 136.37 173.26 182.04 131.32 179.86 196.78 185.69 111.76 173.97
  131.97 198.84 148.54 112.24 172.52 132.3  199.71 197.98 165.61 112.98
  168.69 109.3  102.94 182.3  120.98 137.9  197.35 133.68 129.65 191.82
  111.07 175.96 198.81 190.13 165.17 131.41 125.43 181.93 187.98 152.54
  124.43 111.29 108.72 171.91 142.01 190.54 173.97 119.13 161.38 1

## 7: Find the 90th percentile of batting average.

In [11]:
batting_avg = np.array([df_csv['Batting Average']])
percentile_90 = np.percentile(batting_avg,90)
print(percentile_90)

55.323


## 8: Find the number of players with strike rate above 150.

In [13]:
strike_rate=np.array([df_csv['Strike Rate']])
above_150=np.sum(strike_rate>150)
print(above_150)

513


## 9: Reshape the first 20 batting averages into a 4x5 matrix.

In [14]:
batting_avg=np.array([df_csv['Batting Average'][:20]])
reshape = batting_avg.reshape(4,5)
print(reshape)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


## 10: Compute row-wise sum of reshaped matrix.

In [15]:
matrix=np.array([reshape])
row_wise=np.sum(matrix, axis=1)
print(row_wise)

[[122.13 141.43 159.91 205.15 178.56]]


## 11: Compute column-wise mean of reshaped matrix.

In [16]:
matrix=np.array([reshape])
column_wise=np.mean(matrix, axis=0)
print(column_wise)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


## 12: Transpose the reshaped matrix.

In [17]:
matrix=np.array([reshape])
transpose=matrix.T
print(transpose)

[[[27.7 ]
  [22.2 ]
  [34.59]
  [37.64]]

 [[24.61]
  [38.21]
  [42.43]
  [36.18]]

 [[36.87]
  [40.9 ]
  [39.24]
  [42.9 ]]

 [[51.81]
  [45.78]
  [55.4 ]
  [52.16]]

 [[49.8 ]
  [46.01]
  [41.21]
  [41.54]]]


## 13: Find the variance of batting average.

In [18]:
batting_avg=np.array([df_csv['Batting Average']])
varience=np.var(batting_avg)
print(varience)

131.5398293159


## 14: Stack age and matches played horizontally.

In [19]:
Age=np.array([df_csv['Age']])
Matches=np.array([df_csv['Matches Played']])
stacked = np.hstack((Age.reshape(-1, 1), Matches.reshape(-1, 1)))
print(stacked)

[[ 26 456]
 [ 23 154]
 [ 32 210]
 ...
 [ 23 126]
 [ 35  16]
 [ 30 146]]


## 15: Split the batting average array into 5 equal parts.

In [20]:
batting_avg=np.array(df_csv['Batting Average'])
arr=np.split(batting_avg,5)
print(arr)

[array([27.7 , 24.61, 36.87, 51.81, 49.8 , 22.2 , 38.21, 40.9 , 45.78,
       46.01, 34.59, 42.43, 39.24, 55.4 , 41.21, 37.64, 36.18, 42.9 ,
       52.16, 41.54, 46.47, 49.51, 40.81, 37.07, 55.07, 36.7 , 38.48,
       59.61, 20.01, 27.42, 35.36, 57.3 , 22.8 , 20.38, 22.11, 23.54,
       21.5 , 39.19, 43.23, 30.87, 35.93, 23.67, 33.45, 40.9 , 49.29,
       20.13, 38.69, 31.88, 54.11, 48.62, 43.56, 31.09, 56.41, 21.8 ,
       24.38, 35.67, 24.98, 58.26, 51.92, 30.36, 43.54, 59.29, 55.37,
       44.03, 56.15, 59.57, 49.73, 22.6 , 36.06, 53.51, 29.22, 53.23,
       24.81, 21.88, 35.36, 21.47, 58.29, 53.05, 52.03, 45.19, 28.65,
       40.73, 43.89, 41.  , 30.41, 40.61, 39.65, 59.85, 55.9 , 38.54,
       44.92, 49.91, 21.39, 55.8 , 54.41, 38.3 , 35.65, 30.92, 39.07,
       21.78, 54.09, 21.42, 33.16, 57.26, 49.41, 31.26, 30.11, 20.2 ,
       47.83, 21.95, 41.3 , 58.48, 24.38, 55.78, 59.66, 22.46, 55.32,
       40.64, 56.26, 42.85, 46.48, 41.75, 54.58, 49.36, 40.85, 54.73,
       29.81, 26.29